# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-eventsview-controls-1row-volume-patch

# >> macros
BuildArch: armv7hl
# << macros

Summary:    Eventsview controls patch 1row + Volume
Version:    0.0.2
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   lipstick-jolla-home-qt5 >= 0.23.20.11

%description
Remastered "Eventsview controls patch" showing only rows of switches and row
 with Volume slider in events page.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-eventsview-controls-1row-volume-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-eventsview-controls-1row-volume-patch
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-eventsview-controls-1row-volume-patch
# >> files
# << files
